name: TriSurvival
main: net.trilleo.mc.plugins.trisurvival.Main
version: ${projectVersion}
api-version: 1.21

commands:
  trisurvival:
    description: Main command for the TriSurvival plugin
    usage: /trisurvival <subcommand> [args]
    aliases:
      - ts